server:
  port: 8081

spring:
  application:
    name: settlement-service

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: settlement-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
logging:
  level:
    root: INFO
    com.learning.settlement_service: DEBUG